### ISSUE TITLE
Sample error: “InternalOAuthError: failed to obtain request token”

### ISSUE THREAD

**Issue by repoman** [jaredhanson/passport-twitter#3]
I get this when trying the sample.

This is my callback URL:

`callbackURL: "http://127.0.0.1:3000/auth/twitter/callback"`

InternalOAuthError: failed to obtain request token
    at /Users/frode/Dropbox/Nettsider/signin/node_modules/passport-twitter/node_modules/passport-oauth/lib/passport-oauth/strategies/oauth.js:155:36
    at /Users/frode/Dropbox/Nettsider/signin/node_modules/passport-twitter/node_modules/passport-oauth/node_modules/oauth/lib/oauth.js:510:17
    at passBackControl (/Users/frode/Dropbox/Nettsider/signin/node_modules/passport-twitter/node_modules/passport-oauth/node_modules/oauth/lib/oauth.js:366:13)
    at IncomingMessage.<anonymous> (/Users/frode/Dropbox/Nettsider/signin/node_modules/passport-twitter/node_modules/passport-oauth/node_modules/oauth/lib/oauth.js:378:9)
    at IncomingMessage.emit (events.js:88:20)
    at HTTPParser.onMessageComplete (http.js:137:23)
    at CleartextStream.ondata (http.js:1137:24)
    at CleartextStream._push (tls.js:367:27)
    at SecurePair.cycle (tls.js:688:20)
    at EncryptedStream.write (tls.js:122:13)

**Comment by iammerrick** [comment]
Still seeing this with latest packages....

**Comment by ktkaushik** [comment]
yeah, same here

**Comment by RPGillespie6** [comment]
@ktkaushik Are you sure you have the `tokenURL` set right? I was using GitLab OAuth, and I copy pasted the token URL from their documentation and it turned out to be wrong (if you copy-paste).

**Comment by Pana** [comment]
Same problem here

**Comment by Naeem-gg** [comment]
"InternalOAuthError: failed to obtain request token"
I ran into the same problem with latest "passport-twitter","express", and Node.
Is there any solution out there.
