### ISSUE TITLE
Error: Failed to find request token in session

### ISSUE THREAD

**Issue by swapnesh** [jaredhanson/passport-twitter#48]
Following is the error- 

Error: Failed to find request token in session
        at Strategy.OAuthStrategy.authenticate (/MYPROJECT/node_modules/passport-twitter/node_modules/passport-oauth1/lib/strategy.js:142:54)
        at Strategy.authenticate (/MYPROJECT/node_modules/passport-twitter/lib/strategy.js:85:40)
        at attempt (/MYPROJECT/node_modules/passport/lib/middleware/authenticate.js:337:16)
        at Object.authenticate [as handle] (/MYPROJECT/node_modules/passport/lib/middleware/authenticate.js:338:7)
        at next_layer (/MYPROJECT/node_modules/express/lib/router/route.js:103:13)
        at Route.dispatch (/MYPROJECT/node_modules/express/lib/router/route.js:107:5)
        at /MYPROJECT/node_modules/express/lib/router/index.js:205:24
        at Function.proto.process_params (/MYPROJECT/node_modules/express/lib/router/index.js:269:12)
        at next (/MYPROJECT/node_modules/express/lib/router/index.js:199:19)
        at next (/MYPROJECT/node_modules/express/lib/router/index.js:176:38)

This is the URL I followed for twitter(FYI- facebook signup is working correctly)  http://scotch.io/tutorials/javascript/easy-node-authentication-twitter

My app.js file is - http://pastebin.com/Q9CN6Uvf
My passport.js file is - http://pastebin.com/BggGkzNw
My model is - http://pastebin.com/uN59T636

Let me know what I am doing wrong.

My development URL is like - http://192.XXX.XXX.XX:PORT_NUMBER

I checked settings in my twitter acc multiple times as well, still no luck :(

As a note I am using Express 4.

  "dependencies": {
    "bcrypt-nodejs": "0.0.3",
    "body-parser": "1.2.x",
    "connect-flash": "^0.1.1",
    "cookie-parser": "1.1.x",
    "express": "4.2.x",
    "express-session": "1.2.x",
    "forever": "^0.11.1",
    "mongoose": "3.8.x",
    "passport": "^0.2.0",
    "passport-facebook": "^1.0.3",
    "passport-local": "^1.0.0",
    "passport-twitter": "^1.0.2"
  }

**Comment by championswimmer** [comment]
This is a very late answer, but I just figured another reason this can happen. When the guys who made express-session said that MemoryStore is not meant for production, they really meant it.

If you're using clustering, (pm2 or forever or running on Heroku), then memory based cookie storages have their own set of problems. You'll often loose cookies or corrupt them (because there are two or more separate processes on server side, not sharing common memory).

If you want to run your Node app with clusters, you need to use Redis or some DB-backed cookie storage
