### ISSUE TITLE
Failed to validate oauth signature and token at Strategy.parseErrorResponse 

### ISSUE THREAD

**Issue by matijaabicic** [jaredhanson/passport-twitter#54]
Since #9 is closed, I'm not sure if anyone is looking for posts there. I tried all suggested solutions, still having issues. quadruple-checked consumer key, secret, callback url; my machine syncs to time.apple.com, so I doubt it's off compared to twitter...any ideas?

> Error: Failed to validate oauth signature and token at Strategy.parseErrorResponse (/Users/matijaabicic/work/Development/LicensePlate/node_modules/passport-twitter/lib/strategy.js:178:10) at Strategy.OAuthStrategy._createOAuthError (/Users/matijaabicic/work/Development/LicensePlate/node_modules/passport-twitter/node_modules/passport-oauth1/lib/strategy.js:349:16) at /Users/matijaabicic/work/Development/LicensePlate/node_modules/passport-twitter/node_modules/passport-oauth1/lib/strategy.js:218:41 at /Users/matijaabicic/work/Development/LicensePlate/node_modules/passport-twitter/node_modules/passport-oauth1/node_modules/oauth/lib/oauth.js:543:17 at passBackControl (/Users/matijaabicic/work/Development/LicensePlate/node_modules/passport-twitter/node_modules/passport-oauth1/node_modules/oauth/lib/oauth.js:397:13) at IncomingMessage.<anonymous> (/Users/matijaabicic/work/Development/LicensePlate/node_modules/passport-twitter/node_modules/passport-oauth1/node_modules/oauth/lib/oauth.js:409:9) at IncomingMessage.EventEmitter.emit (events.js:117:20) at _stream_readable.js:920:16 at process._tickCallback (node.js:415:13)

**Comment by matijaabicic** [comment]
never mind, found my mistake. had my secret, key and callback variables inside quotation marks...which, of course made them not-variables
