### ISSUE TITLE
Preferred way to integrate email requesting?

### ISSUE THREAD

**Issue by tayste5000** [jaredhanson/passport-twitter#73]
Twitter recently added permission to access the user's email (app needs to request special permissions and be whitelisted by twitter) through the endpoint:

    .../account/verify_credentials.json?include_email=true

This doesn't work with the method in this repo because it automatically adds:

    ?user_id={users id}

which clashes with ?include_emails=true when you provide the previously mentioned URL as userProfileURL. I would like to submit a pull request that will make this work but am not sure what the preferred route would be. 

I'm guessing we want to minimize the impact that any change would have on apps using this library who aren't trying to get emails. Perhaps we could do:

    ...

    if (this._userProfileURL == ".../account/verify_credentials.json?include_email=true"){
        profileURL = this._userProfileURL
    }
    else{
        profileURL = this._userProfileURL + "?user_id" + params.user_id
    }  
    this._oauth.get(profileURL, token, tokenSecret, ...

but maybe there is a more elegant solution?

Also I would want to add:

    ...
    profile.emails = [{value: json.email}];
    ....

to the profile parsing function (all the other passport-providers generate profile objects that follow this format)

Thoughts?

**Comment by danielstjules** [comment]
I'm just monkey-patching the method for now, but it would be great to see this change in passport-twitter!

**Comment by davidwieler** [comment]
Is this still an issue? I can't for the life of me get the email working with the Twitter strategy

**Comment by danielstjules** [comment]
Yup, still an issue. Quick work around until a PR is made:
``` javascript
var TwitterStrategy = require('passport-twitter').Strategy;
var TwitterParse = require('passport-twitter/lib/profile').parse;

// Need to monkey patch the twitter strategy to allow for email retrieval
// An issue has been opened on github requesting support:
// https://github.com/jaredhanson/passport-twitter/issues/73
// The primary changes involve pointing to /account/verify_credentials.json
// rather than /users/show.json

TwitterStrategy.prototype.userProfile = function(token, tokenSecret, params, done) {
  if (!this._skipExtendedUserProfile) {
    var json;
    var url = 'https://api.twitter.com/1.1/account/verify_credentials.json?' +
      'include_email=true' + '&user_id=' + params.user_id;

    this._oauth.get(url, token, tokenSecret, function (err, body, res) {
      if (err) {
        if (err.data) {
          try {
            json = JSON.parse(err.data);
          } catch (_) {}
        }
        if (json && json.errors && json.errors.length) {
          var e = json.errors[0];
          return done(new Error(e.message, e.code));
        }
        return done(new Error('Failed to fetch user profile', err));
      }

      try {
        json = JSON.parse(body);
      } catch (ex) {
        return done(new Error('Failed to parse user profile'));
      }

      var profile = TwitterParse(json);
      profile.provider = 'twitter';
      profile._raw = body;
      profile._json = json;
      profile._accessLevel = res.headers['x-access-level'];
      done(null, profile);
    });
  } else {
    var profile = { provider: 'twitter' };
    profile.id = params.user_id;
    profile.username = params.screen_name;
    done(null, profile);
  }
};

module.exports = TwitterStrategy;
```

**Comment by davidwieler** [comment]
@danielstjules,

Worked just fine for me. I editing my comment to show a working example, once the App was whitelisted by Twitter of course.

To get whitelisted, use this URL: https://support.twitter.com/forms/platform, select "I need access to special permissions", then enter "Email" into "Permissions Requested"

**Comment by danielstjules** [comment]
Nvm, fixed in 1.0.4 :)

**Comment by cfjedimaster** [comment]
So I'm trying like heck to get emails as well. When I add includeEmail:true to my strategy, and then do 

     app.get('/auth/twitter', passport.authenticate('twitter', {scope:['include_email=true']}));

When I return from my Twitter auth, I get this in my console:

TypeError: Cannot read property '0' of undefined
    at Strategy._verify (c:\projects\snowball\app.js:50:24)
    at c:\projects\snowball\node_modules\passport-oauth1\lib\strategy.js:184:24
    at c:\projects\snowball\node_modules\passport-twitter\lib\strategy.js:158:7
    at passBackControl (c:\projects\snowball\node_modules\oauth\lib\oauth.js:390:11)
    at IncomingMessage.<anonymous> (c:\projects\snowball\node_modules\oauth\lib\oauth.js:409:9)

**Comment by cfjedimaster** [comment]
So it turns out it's related to requesting permission - as commented on above. Should this be documented though?

**Comment by davidwieler** [comment]
@cfjedimaster it really should be. This topic was opened about a year ago, and it still pops up from time to time
