### ISSUE TITLE
Failed to obtain request token

### ISSUE THREAD

**Issue by shenghuowang** [jaredhanson/passport-twitter#81]
after config key and callbackURL(http://127.0.0.1:3000/auth/twitter/callback),when start app, failed to obtain request token,the log as below:
InternalOAuthError: Failed to obtain request token
    at Strategy.OAuthStrategy._createOAuthError (/home/shenghuowangnb/passportjs/node_modules/passport-twitter/node_modules/passport-oauth1/lib/strategy.js:396:17)
    at /home/shenghuowangnb/passportjs/node_modules/passport-twitter/node_modules/passport-oauth1/lib/strategy.js:244:41
    at /home/shenghuowangnb/passportjs/node_modules/passport-twitter/node_modules/passport-oauth1/node_modules/oauth/lib/oauth.js:543:17
    at ClientRequest.<anonymous> (/home/shenghuowangnb/passportjs/node_modules/passport-twitter/node_modules/passport-oauth1/node_modules/oauth/lib/oauth.js:421:9)
    at ClientRequest.emit (events.js:107:17)
    at TLSSocket.socketErrorListener (_http_client.js:271:9)
    at TLSSocket.emit (events.js:129:20)
    at net.js:459:14
    at process._tickCallback (node.js:355:11)

**Comment by soyjavi** [comment]
+1

**Comment by caype** [comment]
+1. still struggling to find a solution to this.

**Comment by William-Charles** [comment]
+1

**Comment by Pana** [comment]
+1

**Comment by amolbc** [comment]
+1

**Comment by Dyceman** [comment]
+1

**Comment by hung3102** [comment]
+1

**Comment by mehmettbaki** [comment]
same here? any İdea

InternalOAuthError: failed to obtain request token
    at /home/memo/basic/node_modules/passport-oauth/lib/passport-oauth/strategies/oauth.js:196:36
    at /home/memo/basic/node_modules/oauth/lib/oauth.js:543:17
    at passBackControl (/home/memo/basic/node_modules/oauth/lib/oauth.js:397:13)
    at IncomingMessage.<anonymous> (/home/memo/basic/node_modules/oauth/lib/oauth.js:409:9)
    at IncomingMessage.emit (node:events:529:35)
    at endReadableNT (node:internal/streams/readable:1368:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
