### ISSUE TITLE
APIError: Bad Authentication data

### ISSUE THREAD

**Issue by CyberKronos** [jaredhanson/passport-twitter#84]
Is anyone else getting an authentication error after the callback redirect?

`APIError: Bad Authentication data.
    at /Users/Kawing/Desktop/social-trading/server/node_modules/passport-twitter/lib/strategy.js:138:23
    at passBackControl (/Users/Kawing/Desktop/social-trading/server/node_modules/oauth/lib/oauth.js:397:13)
    at IncomingMessage.<anonymous> (/Users/Kawing/Desktop/social-trading/server/node_modules/oauth/lib/oauth.js:409:9)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
`

**Comment by jaredhanson** [comment]
Since you closed this, can you describe the solution for others who might encounter this same issue?

**Comment by CyberKronos** [comment]
Silly mistake, forgot to pass done() params
